|Scenario|Result|ErrorMessage|ErrorStack|ErrorNormalized|StartDt|EndDt|
|step__applyupdates_put_applyupdates_createorupdate|failed|(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachineScaleSets/smdtest1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:23.840142|2020-08-20 08:06:24.147375|
|step__applyupdates_put_applyupdates_createorupdateparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:24.155679|2020-08-20 08:06:24.429733|
|step__applyupdates_get_applyupdates_get|failed|3|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 750, in handler     return getter(**args)   File "/home/azext/src/maintenance/azext_maintenance/generated/custom.py", line 33, in maintenance_apply_update_show     apply_update_name=apply_update_name)   File "/home/azext/src/maintenance/azext_maintenance/vendored_sdks/maintenance/operations/_apply_update_operations.py", line 184, in get     map_error(status_code=response.status_||2020-08-20 08:06:24.432420|2020-08-20 08:06:24.672459|
|step__applyupdates_get_applyupdates_getparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:24.675637|2020-08-20 08:06:24.922224|
|step__maintenanceconfigurations_put_maintenanceconfigurations_createorupdateforresource|failed|Operation returned an invalid status 'Bad Request'|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:24.925274|2020-08-20 08:06:25.895999|
|step__maintenanceconfigurations_get_maintenanceconfigurations_getforresource|failed|3|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 750, in handler     return getter(**args)   File "/home/azext/src/maintenance/azext_maintenance/generated/custom.py", line 192, in maintenance_maintenance_configuration_show     resource_name=resource_name)   File "/home/azext/src/maintenance/azext_maintenance/vendored_sdks/maintenance/operations/_maintenance_configuration_operations.py", line 95, in get     map_error(status_cod||2020-08-20 08:06:25.901753|2020-08-20 08:06:26.111109|
|step__maintenanceconfigurations_get_maintenanceconfigurations_list|successed||||2020-08-20 08:06:26.114211|2020-08-20 08:06:27.936996|
|step__maintenanceconfigurations_patch_maintenanceconfigurations_updateforresource|failed|(ResourceNotFound) The Resource 'Microsoft.Maintenance/maintenanceConfigurations/configuration1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:27.939277|2020-08-20 08:06:28.295820|
|step__configurationassignments_put_configurationassignments_createorupdate|failed|(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachineScaleSets/smdtest1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:28.299232|2020-08-20 08:06:28.855868|
|step__configurationassignments_put_configurationassignments_createorupdateparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:28.859613|2020-08-20 08:06:29.393136|
|step__configurationassignments_get_configurationassignments_list|failed|(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachineScaleSets/smdtest1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:29.396247|2020-08-20 08:06:29.598999|
|step__configurationassignments_get_configurationassignments_listparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:29.602000|2020-08-20 08:06:29.825135|
|step__configurationassignments_delete_configurationassignments_deleteparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:29.830653|2020-08-20 08:06:30.093713|
|step__publicmaintenanceconfigurations_get_publicmaintenanceconfigurations_getforresource|failed|3|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 750, in handler     return getter(**args)   File "/home/azext/src/maintenance/azext_maintenance/generated/custom.py", line 20, in maintenance_public_maintenance_configuration_show     return client.get(resource_name=resource_name)   File "/home/azext/src/maintenance/azext_maintenance/vendored_sdks/maintenance/operations/_public_maintenance_configuration_operations.py", line 158,||2020-08-20 08:06:30.096966|2020-08-20 08:06:30.335180|
|step__publicmaintenanceconfigurations_get_publicmaintenanceconfigurations_list|failed|(InvalidResourceType) Resource type 'publicMaintenanceConfigurations' of provider namespace 'Microsoft.Maintenance' was not found in global location for api version '2020-07-01-preview'.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:30.340475|2020-08-20 08:06:30.527244|
|step__updates_get_updates_list|failed|(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachineScaleSets/smdtest1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:30.530175|2020-08-20 08:06:30.781623|
|step__updates_get_updates_listparent|failed|(ParentResourceNotFound) Can not perform requested operation on nested resource. Parent resource 'smdtest1' not found.|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:30.786163|2020-08-20 08:06:31.021698|
|step__configurationassignments_delete_configurationassignments_delete|failed|(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachineScaleSets/smdtest1' under resource group 'clitest6kb3copvxzjpredt6q7wc2euyfd6cgj4ojpjkymcepuuwbyqmhi3ezgcxj637tvpvxmj' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:31.024700|2020-08-20 08:06:31.353035|
|step__maintenanceconfigurations_delete_maintenanceconfigurations_deleteforresource|failed|Operation returned an invalid status 'No Content'|Traceback (most recent call last):   File "/opt/venv/lib/python3.7/site-packages/azure/cli/testsdk/base.py", line 289, in _in_process_execute     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0   File "/opt/venv/lib/python3.7/site-packages/knack/cli.py", line 226, in invoke     exit_code = self.exception_handler(ex)   File "/opt/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 114, in exception_handler     return handle_exception(ex)   File "/opt||2020-08-20 08:06:31.357068|2020-08-20 08:06:31.635992|
Coverage: 1/19
